[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://hffxmntvtsimwlsapfod.functions.supabase.co/functions/v1/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api"
  to = "https://hffxmntvtsimwlsapfod.functions.supabase.co/functions/v1/api"
  status = 200
  force = true

[[redirects]]
  from = "/api/"
  to = "https://hffxmntvtsimwlsapfod.functions.supabase.co/functions/v1/api"
  status = 200
  force = true

[[redirects]]
  from = "/favicon.ico"
  to = "https://mocha-cdn.com/favicon.ico"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200